export type MealSlotKey = "morning" | "noon" | "evening";
export type MealDayKey =
  | "Thứ 2"
  | "Thứ 3"
  | "Thứ 4"
  | "Thứ 5"
  | "Thứ 6"
  | "Thứ 7"
  | "Chủ nhật";

export interface MealSlots {
  morning?: boolean;
  noon?: boolean;
  evening?: boolean;
}

export type WeeklyCutRice = Partial<Record<MealDayKey | string, MealSlots>>;

export interface CutRiceProfile {
  id?: string;
  fullName?: string;
  code?: string;
  rank?: string;
  unit?: string;
}

export interface CutRiceUser {
  id: string;
  username?: string;
  email?: string;
  role?: string;
  Profile?: CutRiceProfile;
  profile?: CutRiceProfile;
}

export interface CutRice {
  id: string;
  userId: string;
  weekly: WeeklyCutRice | null;
  isAutoGenerated: boolean;
  lastUpdated: string | null;
  notes?: string | null;
  User?: CutRiceUser;
  user?: CutRiceUser;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCutRiceRequest {
  userId: string;
  weekly?: WeeklyCutRice | null;
  isAutoGenerated?: boolean | null;
  lastUpdated?: string | null;
  notes?: string | null;
}

export interface UpdateCutRiceRequest {
  userId?: string;
  weekly?: WeeklyCutRice | null;
  isAutoGenerated?: boolean | null;
  lastUpdated?: string | null;
  notes?: string | null;
}

export interface CutRiceQueryRequest extends QueryRequest {
  userId?: string;
  fullName?: string;
  unit?: string;
  isAutoGenerated?: boolean;
}
