/**
 * Danh sách các Query Keys dùng cho React Query
 */
export const QUERY_KEYS = {
  USERS: "users",
  PROFILE: "profile",
  UNIVERSITY_HIERARCHY: "university_hierarchy",
  UNIVERSITIES: "universities",
  ORGANIZATIONS: "organizations",
  EDUCATION_LEVELS: "education_levels",
  CLASSES: "classes",
  DUTY_SCHEDULES: "dutySchedules",
} as const;

/**
 * Danh sach cac Mutation Keys dung cho React Query
 */
export const MUTATION_KEYS = {
  CONFIRM_IDLE: ["__confirm_idle__"],
  MODAL_IDLE: ["__modal_idle__"],
  CHANGE_PASSWORD: [QUERY_KEYS.USERS, "change-password"],
  UPDATE_PROFILE: [QUERY_KEYS.PROFILE, "update"],
  CREATE_USER: [QUERY_KEYS.USERS, "create"],
  UPDATE_USER: [QUERY_KEYS.USERS, "update"],
  CREATE_BATCH_USERS: [QUERY_KEYS.USERS, "create-batch"],
  UPDATE_BATCH_STUDENTS: [QUERY_KEYS.USERS, "update-batch-students"],
  RESET_USER_PASSWORD: [QUERY_KEYS.USERS, "reset-password"],
  TOGGLE_USER_ACTIVE: [QUERY_KEYS.USERS, "toggle-active"],
  DELETE_USER: [QUERY_KEYS.USERS, "delete"],
  CREATE_UNIVERSITY: [QUERY_KEYS.UNIVERSITIES, "create"],
  UPDATE_UNIVERSITY: [QUERY_KEYS.UNIVERSITIES, "update"],
  TOGGLE_UNIVERSITY_STATUS: [QUERY_KEYS.UNIVERSITIES, "toggle-status"],
  DELETE_UNIVERSITY: [QUERY_KEYS.UNIVERSITIES, "delete"],
  CREATE_ORGANIZATION: [QUERY_KEYS.ORGANIZATIONS, "create"],
  UPDATE_ORGANIZATION: [QUERY_KEYS.ORGANIZATIONS, "update"],
  TOGGLE_ORGANIZATION_STATUS: [QUERY_KEYS.ORGANIZATIONS, "toggle-status"],
  DELETE_ORGANIZATION: [QUERY_KEYS.ORGANIZATIONS, "delete"],
  CREATE_EDUCATION_LEVEL: [QUERY_KEYS.EDUCATION_LEVELS, "create"],
  UPDATE_EDUCATION_LEVEL: [QUERY_KEYS.EDUCATION_LEVELS, "update"],
  DELETE_EDUCATION_LEVEL: [QUERY_KEYS.EDUCATION_LEVELS, "delete"],
  CREATE_CLASS: [QUERY_KEYS.CLASSES, "create"],
  UPDATE_CLASS: [QUERY_KEYS.CLASSES, "update"],
  DELETE_CLASS: [QUERY_KEYS.CLASSES, "delete"],
  CREATE_DUTY_SCHEDULE: [QUERY_KEYS.DUTY_SCHEDULES, "create"],
  UPDATE_DUTY_SCHEDULE: [QUERY_KEYS.DUTY_SCHEDULES, "update"],
  DELETE_DUTY_SCHEDULE: [QUERY_KEYS.DUTY_SCHEDULES, "delete"],
} as const;
