const db = require('../models');
const { NotFoundError } = require('../utils/apiError');
const { paginateQuery } = require('../utils/response');

const Commander = db.commander;
const User = db.user;
const Student = db.student;
const YearlyResult = db.yearlyResult;
const TimeTable = db.timeTable;
const CutRice = db.cutRice;
const Achievement = db.achievement;
const YearlyAchievement = db.yearlyAchievement;
const TuitionFee = db.tuitionFee;
const Notification = db.notification;

// ===================== CRUD Cơ bản =====================

const create = async (data) => Commander.create(data);
const getAll = async (query) => paginateQuery(Commander, query, {
  filterFields: ['code', 'fullName', 'gender', 'unit', 'rank', 'organization'],
  include: [{ model: User, attributes: { exclude: ['password', 'refreshToken'] } }],
});

const getDetail = async (id) => {
  const record = await Commander.findByPk(id, {
    include: [{ model: User, attributes: { exclude: ['password', 'refreshToken'] } }],
  });
  if (!record) throw new NotFoundError('Không tìm thấy chỉ huy');
  return record;
};

const update = async (id, data) => {
  const record = await getDetail(id);
  return record.update(data);
};

const deleteRecord = async (id) => {
  const record = await getDetail(id);
  await record.destroy();
  return { deleted: true };
};

// ===================== CH-06: Tự động sinh lịch cắt cơm =====================

const generateCutRice = async (studentId) => {
  const timetables = await TimeTable.findAll({ where: { userId: studentId } });
  if (!timetables.length) throw new NotFoundError('Không có thời khóa biểu để tạo lịch cắt cơm');

  const weekly = {};
  for (const tt of timetables) {
    const schedules = tt.schedules;
    if (!schedules || !Array.isArray(schedules)) continue;

    for (const s of schedules) {
      const day = s.day;
      if (!day) continue;

      if (!weekly[day]) weekly[day] = { morning: false, noon: false, afternoon: false, evening: false };

      const startHour = parseInt(s.startTime?.split(':')[0]) || 0;
      const endHour = parseInt(s.endTime?.split(':')[0]) || 0;

      if (startHour < 10 || endHour <= 10) weekly[day].morning = true;
      if ((startHour >= 10 && startHour < 13) || (endHour > 10 && endHour <= 13)) weekly[day].noon = true;
      if ((startHour >= 13 && startHour < 17) || (endHour > 13 && endHour <= 17)) weekly[day].afternoon = true;
      if (startHour >= 17 || endHour >= 17) weekly[day].evening = true;
    }
  }

  let record = await CutRice.findOne({ where: { userId: studentId } });
  if (record) {
    await record.update({ weekly, isAutoGenerated: true, lastUpdated: new Date() });
  } else {
    record = await CutRice.create({ userId: studentId, weekly, isAutoGenerated: true, lastUpdated: new Date() });
  }

  const User = db.user;
  const user = await User.findByPk(studentId);
  if (user) {
    await Notification.create({
      userId: user.id,
      title: 'Lịch cắt cơm đã được cập nhật',
      content: 'Lịch cắt cơm tuần này đã được cập nhật tự động từ thời khóa biểu.',
      type: 'CUT_RICE',
    });
  }

  return record;
};

const generateAllCutRice = async () => {
  const students = await Student.findAll({ attributes: ['id'] });
  let success = 0, skipped = 0;

  for (const s of students) {
    try {
      const timetables = await TimeTable.findAll({ where: { userId: s.id } });
      if (!timetables.length) { skipped++; continue; }

      const weekly = {};
      for (const tt of timetables) {
        const schedules = tt.schedules;
        if (!schedules || !Array.isArray(schedules)) continue;

        for (const sch of schedules) {
          const day = sch.day;
          if (!day) continue;

          if (!weekly[day]) weekly[day] = { morning: false, noon: false, afternoon: false, evening: false };

          const startHour = parseInt(sch.startTime?.split(':')[0]) || 0;
          const endHour = parseInt(sch.endTime?.split(':')[0]) || 0;

          if (startHour < 10 || endHour <= 10) weekly[day].morning = true;
          if ((startHour >= 10 && startHour < 13) || (endHour > 10 && endHour <= 13)) weekly[day].noon = true;
          if ((startHour >= 13 && startHour < 17) || (endHour > 13 && endHour <= 17)) weekly[day].afternoon = true;
          if (startHour >= 17 || endHour >= 17) weekly[day].evening = true;
        }
      }

      let record = await CutRice.findOne({ where: { userId: s.id } });
      if (record) {
        await record.update({ weekly, isAutoGenerated: true, lastUpdated: new Date() });
      } else {
        await CutRice.create({ userId: s.id, weekly, isAutoGenerated: true, lastUpdated: new Date() });
      }

      await Notification.create({
        userId: s.id,
        title: 'Lịch cắt cơm đã được cập nhật',
        content: 'Lịch cắt cơm tuần này đã được cập nhật tự động.',
        type: 'CUT_RICE',
      });
      success++;
    } catch (e) {
      skipped++;
    }
  }

  return { success, skipped };
};

// ===================== CH-09: Báo cáo thống kê =====================

const getAcademicReport = async (query = {}) => {
  const where = {};
  if (query.schoolYear) where.schoolYear = query.schoolYear;

  const results = await YearlyResult.findAll({
    where,
    include: [{ model: User, include: [{ model: db.profile }] }],
  });

  const summary = {
    totalStudents: results.length,
    averageCpa4: results.length
      ? (results.reduce((s, r) => s + (r.averageGrade4 || 0), 0) / results.length).toFixed(2)
      : 0,
    averageCpa10: results.length
      ? (results.reduce((s, r) => s + (r.averageGrade10 || 0), 0) / results.length).toFixed(2)
      : 0,
    totalPassedSubjects: results.reduce((s, r) => s + (r.passedSubjects || 0), 0),
    totalFailedSubjects: results.reduce((s, r) => s + (r.failedSubjects || 0), 0),
    byStatus: {},
  };

  for (const r of results) {
    const status = r.academicStatus || 'KHÔNG XÁC ĐỊNH';
    summary.byStatus[status] = (summary.byStatus[status] || 0) + 1;
  }

  return { detail: results, summary };
};

const getPartyTrainingReport = async (query = {}) => {
  const where = {};
  if (query.schoolYear) where.schoolYear = query.schoolYear;

  const results = await YearlyResult.findAll({
    where,
    include: [{ model: User, include: [{ model: db.profile }] }],
  });

  const partySummary = {};
  const trainingSummary = {};

  for (const r of results) {
    const pr = r.partyRating || 'CHƯA XẾP LOẠI';
    const tr = r.trainingRating || 'CHƯA XẾP LOẠI';
    partySummary[pr] = (partySummary[pr] || 0) + 1;
    trainingSummary[tr] = (trainingSummary[tr] || 0) + 1;
  }

  return { detail: results, partySummary, trainingSummary };
};

const getAchievementReport = async () => {
  const achievements = await Achievement.findAll({
    include: [{ model: User, include: [{ model: db.profile }] }],
    order: [['year', 'DESC']],
  });

  const yearlyAchievements = await YearlyAchievement.findAll({
    include: [{ model: User, include: [{ model: db.profile }] }],
    order: [['year', 'DESC']],
  });

  const summary = {
    totalAchievements: achievements.length,
    totalYearlyAchievements: yearlyAchievements.length,
    ministryRewardCount: yearlyAchievements.filter(a => a.hasMinistryReward).length,
    nationalRewardCount: yearlyAchievements.filter(a => a.hasNationalReward).length,
    byAward: {},
  };

  for (const a of achievements) {
    const award = a.award || 'KHÔNG XÁC ĐỊNH';
    summary.byAward[award] = (summary.byAward[award] || 0) + 1;
  }

  return { achievements, yearlyAchievements, summary };
};

const getTuitionReport = async (query = {}) => {
  const where = {};
  if (query.schoolYear) where.schoolYear = query.schoolYear;
  if (query.semester) where.semester = query.semester;

  const fees = await TuitionFee.findAll({
    where,
    include: [{ model: User, include: [{ model: db.profile }] }],
  });

  const summary = {
    totalAmount: fees.reduce((s, f) => s + parseFloat(f.totalAmount || 0), 0),
    totalStudents: fees.length,
    paid: fees.filter(f => f.status === 'PAID').length,
    unpaid: fees.filter(f => f.status === 'UNPAID').length,
    byStatus: {},
  };

  for (const f of fees) {
    const status = f.status || 'UNKNOWN';
    summary.byStatus[status] = (summary.byStatus[status] || 0) + 1;
  }

  return { detail: fees, summary };
};

module.exports = {
  create,
  getAll,
  getDetail,
  update,
  delete: deleteRecord,
  generateCutRice,
  generateAllCutRice,
  getAcademicReport,
  getPartyTrainingReport,
  getAchievementReport,
  getTuitionReport,
};
