const db = require('../models');
const User = db.user;
const { NotFoundError } = require('../utils/apiError');
const { paginateQuery } = require('../utils/response');

const CutRice = db.cutRice;
const Student = db.student;

const create = async (data) => CutRice.create(data);
const getAll = async (query) => {
  const profileWhere = {};
  const include = [{ model: User, include: [{ model: db.profile }] }];

  if (query.fullName) profileWhere.fullName = { [db.Sequelize.Op.like]: `%${query.fullName}%` };
  if (query.unit) profileWhere.unit = query.unit;

  if (Object.keys(profileWhere).length > 0) {
    include[0].include[0].where = profileWhere;
    include[0].include[0].required = true;
    include[0].required = true;
  }

  const result = await paginateQuery(CutRice, query, {
    filterFields: ['userId', 'isAutoGenerated'],
    include,
  });

  result.rows = result.rows.map(row => {
    const plain = row.get({ plain: true });
    const weekly = plain.weekly || {};
    const dayMap = {
      'Thứ 2': ['Thứ 2', 'thứ 2'],
      'Thứ 3': ['Thứ 3', 'thứ 3'],
      'Thứ 4': ['Thứ 4', 'thứ 4'],
      'Thứ 5': ['Thứ 5', 'thứ 5'],
      'Thứ 6': ['Thứ 6', 'thứ 6'],
      'Thứ 7': ['Thứ 7', 'thứ 7'],
      'Chủ nhật': ['Chủ nhật', 'chủ nhật'],
    };
    for (const [day, keys] of Object.entries(dayMap)) {
      const slot = weekly[keys[0]] || weekly[keys[1]] || {};
      plain[day + '_sáng'] = slot.morning || false;
      plain[day + '_trưa'] = slot.noon || false;
      plain[day + '_tối'] = slot.evening || false;
    }
    return plain;
  });

  return result;
};

const getDetail = async (id) => {
  const record = await CutRice.findByPk(id, {
    include: [{ model: User, include: [{ model: db.profile }] }],
  });
  if (!record) throw new NotFoundError('Không tìm thấy lịch cắt cơm');
  return record;
};

const update = async (id, data) => {
  const record = await getDetail(id);
  return record.update(data);
};

const deleteRecord = async (id) => {
  const record = await getDetail(id);
  await record.destroy();
  return { deleted: true };
};

// ===================== Export Excel =====================

const exportCutRice = async (query) => {
  const profileWhere = {};
  const include = [{ model: User, include: [{ model: db.profile }] }];

  if (query.studentId) {
    profileWhere.id = query.studentId;
  }
  if (query.unit) {
    profileWhere.unit = query.unit;
  }
  if (query.fullName) {
    profileWhere.fullName = { [db.Sequelize.Op.like]: `%${query.fullName}%` };
  }

  if (Object.keys(profileWhere).length > 0) {
    include[0].include[0].where = profileWhere;
    include[0].include[0].required = true;
    include[0].required = true;
  }

  const records = await CutRice.findAll({ include });

  const ExcelJS = require('exceljs');
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Lịch cắt cơm');

  const dayHeaders = ['Sáng', 'Trưa', 'Tối'];
  const days = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ nhật'];
  const dayKeyLower = ['thứ 2', 'thứ 3', 'thứ 4', 'thứ 5', 'thứ 6', 'thứ 7', 'chủ nhật'];

  const headers = ['Đơn vị', 'Họ và tên', 'MSSV', ...days.flatMap(d => dayHeaders.map(t => `${d} ${t}`))];
  worksheet.addRow(headers);

  for (const record of records) {
    const profile = record.User?.Profile;
    const weekly = record.weekly || {};
    const row = [
      profile?.unit || '',
      profile?.fullName || '',
      profile?.code || '',
    ];

    for (let i = 0; i < days.length; i++) {
      const slot = weekly[days[i]] || weekly[dayKeyLower[i]] || {};
      row.push(slot.morning ? 'x' : '');
      row.push(slot.noon ? 'x' : '');
      row.push(slot.evening ? 'x' : '');
    }
    worksheet.addRow(row);
  }

  worksheet.columns.forEach(col => { col.width = 13; });
  worksheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  worksheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
  worksheet.getRow(1).alignment = { wrapText: true, horizontal: 'center' };

  return workbook.xlsx.writeBuffer();
};

module.exports = { create, getAll, getDetail, update, delete: deleteRecord, exportCutRice };
