const db = require('../models');
const { NotFoundError, BadRequestError } = require('../utils/apiError');
const { paginateQuery } = require('../utils/response');

const Student = db.student;
const YearlyResult = db.yearlyResult;
const SemesterResult = db.semesterResult;
const SubjectResult = db.subjectResult;
const TimeTable = db.timeTable;
const CutRice = db.cutRice;
const Achievement = db.achievement;
const AchievementProfile = db.achievementProfile;
const YearlyAchievement = db.yearlyAchievement;
const ScientificInitiative = db.scientificInitiative;
const ScientificTopic = db.scientificTopic;
const TuitionFee = db.tuitionFee;
const Notification = db.notification;

// ===================== CRUD Cơ bản =====================

const create = async (data) => Student.create(data);
const getAll = async (query) => paginateQuery(Student, query, { filterFields: ['studentId', 'fullName', 'gender', 'enrollment', 'unit', 'rank', 'classId', 'organizationId', 'universityId', 'educationLevelId'] });

const getDetail = async (id) => {
  const record = await Student.findByPk(id);
  if (!record) throw new NotFoundError('Không tìm thấy học viên');
  return record;
};

const update = async (id, data) => {
  const record = await getDetail(id);
  return record.update(data);
};

const deleteRecord = async (id) => {
  const record = await getDetail(id);
  await record.destroy();
  return { deleted: true };
};

// ===================== HV-02: Profile (xem profile dùng /api/auth/profile) =====================

const updateProfile = async (studentId, data) => {
  const student = await Student.findByPk(studentId);
  if (!student) throw new NotFoundError('Không tìm thấy học viên');

  const allowedFields = [
    'currentAddress', 'phoneNumber', 'email', 'avatar',
    'rank', 'unit', 'positionGovernment', 'positionParty',
  ];
  const updateData = {};
  for (const key of allowedFields) {
    if (data[key] !== undefined) updateData[key] = data[key];
  }

  return student.update(updateData);
};

const uploadAvatar = async (studentId, avatarUrl) => {
  const student = await Student.findByPk(studentId);
  if (!student) throw new NotFoundError('Không tìm thấy học viên');
  return student.update({ avatar: avatarUrl });
};

// ===================== HV-03: Academic Results =====================

const getAcademicResults = async (studentId, query = {}) => {
  const where = { studentId };
  if (query.schoolYear) where.schoolYear = query.schoolYear;

  return YearlyResult.findAll({
    where,
    include: [{
      model: SemesterResult,
      include: [{ model: SubjectResult }],
    }],
    order: [['schoolYear', 'DESC']],
  });
};

// ===================== HV-06: TimeTable =====================

const getMyTimeTable = async (studentId) => {
  return TimeTable.findAll({ where: { studentId } });
};

const createMyTimeTable = async (studentId, data) => {
  return TimeTable.create({ ...data, studentId });
};

const updateMyTimeTable = async (studentId, id, data) => {
  const record = await TimeTable.findOne({ where: { id, studentId } });
  if (!record) throw new NotFoundError('Không tìm thấy thời khóa biểu');
  return record.update(data);
};

const deleteMyTimeTable = async (studentId, id) => {
  const record = await TimeTable.findOne({ where: { id, studentId } });
  if (!record) throw new NotFoundError('Không tìm thấy thời khóa biểu');
  await record.destroy();
  return { deleted: true };
};

// ===================== HV-07: Cut Rice =====================

const getMyCutRice = async (studentId) => {
  let record = await CutRice.findOne({ where: { studentId } });
  if (!record) {
    record = await CutRice.create({ studentId, weekly: {} });
  }
  return record;
};

const updateMyCutRice = async (studentId, data) => {
  let record = await CutRice.findOne({ where: { studentId } });
  if (!record) {
    record = await CutRice.create({ studentId, weekly: {} });
  }

  return record.update({
    weekly: data.weekly !== undefined ? data.weekly : record.weekly,
    isAutoGenerated: false,
    notes: data.notes !== undefined ? data.notes : record.notes,
    lastUpdated: new Date(),
  });
};

// ===================== HV-08: Achievements & Tuition =====================

const getMyAchievements = async (studentId) => {
  const achievements = await Achievement.findAll({ where: { studentId }, order: [['year', 'DESC']] });
  const profile = await AchievementProfile.findOne({ where: { studentId } });
  const yearlyAchievements = await YearlyAchievement.findAll({
    where: { studentId },
    include: [{ model: ScientificInitiative }, { model: ScientificTopic }],
    order: [['year', 'DESC']],
  });
  return { achievements, profile, yearlyAchievements };
};

const getMyTuitionFees = async (studentId) => {
  return TuitionFee.findAll({ where: { studentId }, order: [['createdAt', 'DESC']] });
};

// ===================== HV-09: Notifications =====================

const getMyNotifications = async (userId, query = {}) => {
  const where = { studentId };
  if (query.type) where.type = query.type;
  if (query.isRead !== undefined) where.isRead = query.isRead === 'true';

  return paginateQuery(Notification, query, { where, order: [['createdAt', 'DESC']] });
};

const getMyNotificationDetail = async (userId, id) => {
  const notif = await Notification.findOne({ where: { id, studentId } });
  if (!notif) throw new NotFoundError('Không tìm thấy thông báo');
  await notif.update({ isRead: true });
  return notif;
};

const markNotificationRead = async (userId, id) => {
  const notif = await Notification.findOne({ where: { id, studentId } });
  if (!notif) throw new NotFoundError('Không tìm thấy thông báo');
  return notif.update({ isRead: true });
};

const markAllNotificationsRead = async (userId) => {
  await Notification.update({ isRead: true }, { where: { userId } });
  return { updated: true };
};

module.exports = {
  create,
  getAll,
  getDetail,
  update,
  delete: deleteRecord,
  uploadAvatar,
  getAcademicResults,
  getMyTimeTable,
  createMyTimeTable,
  updateMyTimeTable,
  deleteMyTimeTable,
  getMyCutRice,
  updateMyCutRice,
  getMyAchievements,
  getMyTuitionFees,
  getMyNotifications,
  getMyNotificationDetail,
  markNotificationRead,
  markAllNotificationsRead,
};
