const router = require('express').Router();
const controller = require('../controllers/commander.controller');
const { authMiddleware, requireRole } = require('../middlewares/auth.middleware');

router.use(authMiddleware);
router.use(requireRole('ADMIN', 'COMMANDER'));

/**
 * @swagger
 * /commanders/cut-rice/generate/{studentId}:
 *   post:
 *     tags: [Commanders]
 *     summary: CH-06 - Tự động sinh lịch cắt cơm cho 1 học viên
 *     description: Dựa vào thời khóa biểu (timeTables.schedules), hệ thống tự động tính toán và tạo lịch cắt cơm (sáng/trưa/chiều/tối) cho học viên. isAutoGenerated = true
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: studentId
 *         in: path
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Lịch cắt cơm đã được tạo
 */
router.post('/cut-rice/generate/:studentId', controller.generateCutRice);

/**
 * @swagger
 * /commanders/cut-rice/generate-all:
 *   post:
 *     tags: [Commanders]
 *     summary: CH-06 - Tự động sinh lịch cắt cơm cho tất cả học viên
 *     description: Quét thời khóa biểu của tất cả học viên, tự động tạo lịch cắt cơm và gửi thông báo. Trả về số lượng thành công/bỏ qua
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Kết quả tạo hàng loạt { success, skipped }
 */
router.post('/cut-rice/generate-all', controller.generateAllCutRice);

/**
 * @swagger
 * /commanders/reports/academic:
 *   get:
 *     tags: [Commanders]
 *     summary: CH-09 - Báo cáo thống kê học tập
 *     description: Thống kê điểm trung bình GPA/CPA, số môn đạt/rớt, phân loại học tập theo năm học
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: schoolYear
 *         in: query
 *         schema: { type: string }
 *         description: Lọc theo năm học
 *     responses:
 *       200:
 *         description: Báo cáo học tập { detail, summary }
 */
router.get('/reports/academic', controller.getAcademicReport);

/**
 * @swagger
 * /commanders/reports/party-training:
 *   get:
 *     tags: [Commanders]
 *     summary: CH-09 - Báo cáo xếp loại Đảng viên & Đoàn viên
 *     description: Thống kê xếp loại Đảng (partyRating) và rèn luyện (trainingRating) theo năm học
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: schoolYear
 *         in: query
 *         schema: { type: string }
 *         description: Lọc theo năm học
 *     responses:
 *       200:
 *         description: Báo cáo xếp loại { detail, partySummary, trainingSummary }
 */
router.get('/reports/party-training', controller.getPartyTrainingReport);

/**
 * @swagger
 * /commanders/reports/achievements:
 *   get:
 *     tags: [Commanders]
 *     summary: CH-09 - Báo cáo thống kê khen thưởng
 *     description: Tổng hợp thành tích, khen thưởng Bộ/Quốc gia, phân loại theo danh hiệu
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Báo cáo khen thưởng { achievements, yearlyAchievements, summary }
 */
router.get('/reports/achievements', controller.getAchievementReport);

/**
 * @swagger
 * /commanders/reports/tuition:
 *   get:
 *     tags: [Commanders]
 *     summary: CH-09 - Báo cáo thống kê học phí
     *     description: Tổng hợp tình trạng học phí (đã thanh toán, chưa thanh toán, còn nợ)
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: schoolYear
 *         in: query
 *         schema: { type: string }
 *         description: Lọc theo năm học
 *       - name: semester
 *         in: query
 *         schema: { type: string }
 *         description: Lọc theo học kỳ
 *     responses:
 *       200:
 *         description: Báo cáo học phí { detail, summary }
 */
router.get('/reports/tuition', controller.getTuitionReport);

// CRUD Chỉ huy
router.post('/', controller.create);
router.get('/', controller.getAll);
router.get('/:id', controller.getDetail);
router.put('/:id', controller.update);
router.delete('/:id', controller.delete);

module.exports = router;
