const router = require('express').Router();
const controller = require('../controllers/student.controller');
const { authMiddleware, requireRole, requireStudent } = require('../middlewares/auth.middleware');

// ===================== Học viên tự truy cập =====================
router.use(authMiddleware);

/**
 * @swagger
 * /students/profile:
 *   get:
 *     tags: [Students]
 *     summary: HV-02 - Xem thông tin cá nhân
 *     description: Học viên xem hồ sơ cá nhân bao gồm thông tin lớp, đơn vị, trường, trình độ đào tạo
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Thông tin cá nhân học viên
 */
router.get('/profile', requireStudent, controller.getProfile);

/**
 * @swagger
 * /students/profile:
 *   put:
 *     tags: [Students]
 *     summary: HV-02 - Cập nhật thông tin cá nhân
 *     description: Học viên tự cập nhật địa chỉ, số điện thoại, email, ảnh đại diện, cấp bậc, chức vụ
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Cập nhật thành công
 */
router.put('/profile', requireStudent, controller.updateProfile);

/**
 * @swagger
 * /students/avatar:
 *   post:
 *     tags: [Students]
 *     summary: HV-02 - Upload ảnh đại diện
 *     description: Học viên cập nhật ảnh đại diện cá nhân
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Cập nhật ảnh đại diện thành công
 */
router.post('/avatar', requireStudent, controller.uploadAvatar);

/**
 * @swagger
 * /students/results:
 *   get:
 *     tags: [Students]
 *     summary: HV-03 - Xem kết quả học tập
 *     description: Học viên xem bảng điểm chi tiết theo năm học, bao gồm GPA/CPA từng học kỳ và môn học. Hỗ trợ lọc theo schoolYear
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: schoolYear
 *         in: query
 *         schema: { type: string }
     *         description: Lọc theo năm học, ví dụ 2024-2025
 *     responses:
 *       200:
 *         description: Danh sách kết quả học tập
 */
router.get('/results', requireStudent, controller.getAcademicResults);

/**
 * @swagger
 * /students/time-table:
 *   get:
 *     tags: [Students]
 *     summary: HV-06 - Xem thời khóa biểu cá nhân
 *     description: Học viên xem thời khóa biểu học tập của mình
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Danh sách thời khóa biểu
 *   post:
 *     tags: [Students]
 *     summary: HV-06 - Thêm môn học vào TKB
 *     description: Học viên thêm môn tự chọn vào thời khóa biểu cá nhân. Hệ thống kiểm tra trùng lịch
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       201:
 *         description: Thêm môn học thành công
 */
router.get('/time-table', requireStudent, controller.getMyTimeTable);
router.post('/time-table', requireStudent, controller.createMyTimeTable);

/**
 * @swagger
 * /students/time-table/{id}:
 *   put:
 *     tags: [Students]
 *     summary: HV-06 - Sửa môn học trong TKB
 *     description: Học viên điều chỉnh thời khóa biểu cá nhân
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Cập nhật thành công
 *   delete:
 *     tags: [Students]
 *     summary: HV-06 - Xóa môn học khỏi TKB
 *     description: Học viên xóa môn học khỏi thời khóa biểu cá nhân
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Xóa thành công
 */
router.put('/time-table/:id', requireStudent, controller.updateMyTimeTable);
router.delete('/time-table/:id', requireStudent, controller.deleteMyTimeTable);

/**
 * @swagger
 * /students/cut-rice:
 *   get:
 *     tags: [Students]
 *     summary: HV-07 - Xem lịch cắt cơm
 *     description: Học viên xem lịch cắt cơm tuần hiện tại (sáng/trưa/chiều/tối). Tự động tạo nếu chưa có
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Lịch cắt cơm
 *   put:
 *     tags: [Students]
 *     summary: HV-07 - Điều chỉnh lịch cắt cơm thủ công
 *     description: Học viên tự đăng ký thêm hoặc hủy bữa ăn. isAutoGenerated chuyển thành false
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Cập nhật lịch cắt cơm thành công
 */
router.get('/cut-rice', requireStudent, controller.getMyCutRice);
router.put('/cut-rice', requireStudent, controller.updateMyCutRice);

/**
 * @swagger
 * /students/achievements:
 *   get:
 *     tags: [Students]
 *     summary: HV-08 - Xem thành tích cá nhân
 *     description: Học viên xem danh sách khen thưởng, hồ sơ thành tích, thành tích theo năm (kèm sáng kiến/đề tài NCKH)
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Danh sách thành tích
 */
router.get('/achievements', requireStudent, controller.getMyAchievements);

/**
 * @swagger
 * /students/tuition-fees:
 *   get:
 *     tags: [Students]
 *     summary: HV-08 - Xem học phí
 *     description: Học viên xem danh sách học phí phải đóng, đã đóng, còn nợ theo học kỳ
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Danh sách học phí
 */
router.get('/tuition-fees', requireStudent, controller.getMyTuitionFees);

/**
 * @swagger
 * /students/notifications:
 *   get:
 *     tags: [Students]
 *     summary: HV-09 - Xem danh sách thông báo
 *     description: Học viên xem danh sách thông báo của mình. Hỗ trợ lọc theo type và isRead
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: type
 *         in: query
 *         schema: { type: string }
 *         description: Lọc theo loại thông báo (GENERAL, GRADE, CUT_RICE, ACHIEVEMENT)
 *       - name: isRead
 *         in: query
 *         schema: { type: string, enum: ['true', 'false'] }
 *         description: Lọc theo trạng thái đọc
 *     responses:
 *       200:
 *         description: Danh sách thông báo
 */
router.get('/notifications', requireStudent, controller.getMyNotifications);

/**
 * @swagger
 * /students/notifications/read-all:
 *   put:
 *     tags: [Students]
 *     summary: HV-09 - Đánh dấu đọc tất cả thông báo
 *     description: Học viên đánh dấu tất cả thông báo là đã đọc
 *     security: [{ BearerAuth: [] }]
 *     responses:
 *       200:
 *         description: Đã đánh dấu đọc tất cả
 */
router.put('/notifications/read-all', requireStudent, controller.markAllNotificationsRead);

/**
 * @swagger
 * /students/notifications/{id}:
 *   get:
 *     tags: [Students]
 *     summary: HV-09 - Xem chi tiết thông báo
 *     description: Học viên xem chi tiết thông báo, tự động đánh dấu đã đọc
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Chi tiết thông báo
 *   put:
 *     tags: [Students]
 *     summary: HV-09 - Đánh dấu đọc 1 thông báo
 *     description: Học viên đánh dấu 1 thông báo là đã đọc
 *     security: [{ BearerAuth: [] }]
 *     parameters:
 *       - name: id
 *         in: path
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Đã đánh dấu đọc
 */
router.get('/notifications/:id', requireStudent, controller.getMyNotificationDetail);
router.put('/notifications/:id/read', requireStudent, controller.markNotificationRead);

// ===================== Chỉ huy / Admin quản lý toàn bộ =====================
router.use(requireRole('ADMIN', 'COMMANDER'));

router.post('/', controller.create);
router.get('/', controller.getAll);
router.get('/:id', controller.getDetail);
router.put('/:id', controller.update);
router.delete('/:id', controller.delete);

module.exports = router;
