"use client";

import { useMemo } from "react";
import { ColumnDef } from "@tanstack/react-table";
import { HiOutlineDownload, HiOutlineRefresh } from "react-icons/hi";
import ActionButton from "@/library/ActionButton";
import Badge from "@/library/Badge";
import Button from "@/library/Button";
import ErrorState from "@/library/ErrorState";
import Table from "@/library/Table";
import Typography from "@/library/Typography";
import { FilterField } from "@/library/table/TableFilter";
import useAppMutation from "@/hooks/useAppMutation";
import useTableQuery from "@/hooks/useTableQuery";
import { MUTATION_KEYS, QUERY_KEYS } from "@/constants/query-keys";
import { cutRiceService } from "@/services/cut-rice";
import { formatDateTime } from "@/utils/fn-common";
import { CutRice } from "@/types/cut-rice";
import CutRiceSkeleton from "./CutRiceSkeleton";

const mealDays = ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ nhật"];

const getStudentName = (record: CutRice) =>
  record.User?.Profile?.fullName || record.User?.username || record.userId;

export default function CutRiceTab() {
  const cutRice = useTableQuery<CutRice>({
    queryKey: [QUERY_KEYS.CUT_RICE],
    fetchData: cutRiceService.getCutRiceList,
  });

  const generateAllMutation = useAppMutation({
    mutationKey: MUTATION_KEYS.GENERATE_ALL_CUT_RICE,
    mutationFn: cutRiceService.generateAll,
    invalidateQueryKey: [QUERY_KEYS.CUT_RICE],
    successMessage: "Tạo lịch cắt cơm tự động thành công!",
    errorMessage: "Tạo lịch cắt cơm thất bại!",
  });

  const generateOneMutation = useAppMutation({
    mutationKey: MUTATION_KEYS.GENERATE_CUT_RICE,
    mutationFn: (userId: string) => cutRiceService.generateForStudent(userId),
    invalidateQueryKey: [QUERY_KEYS.CUT_RICE],
    successMessage: "Tạo lại lịch cắt cơm thành công!",
    errorMessage: "Tạo lại lịch cắt cơm thất bại!",
  });

  const columns = useMemo<ColumnDef<CutRice>[]>(
    () => [
      {
        id: "student",
        header: "Học viên",
        meta: { noWrap: true },
        cell: (info) => (
          <div>
            <Typography variant="body" weight="semibold" color="neutral">
              {getStudentName(info.row.original)}
            </Typography>
            <Typography variant="caption" color="gray">
              {info.row.original.User?.Profile?.unit || info.row.original.userId}
            </Typography>
          </div>
        ),
      },
      {
        id: "auto",
        header: "Trạng thái",
        cell: (info) => (
          <Badge variant={info.row.original.isAutoGenerated ? "success" : "warning"}>
            {info.row.original.isAutoGenerated ? "Tự động" : "Thủ công"}
          </Badge>
        ),
      },
      {
        id: "weekly",
        header: "Lịch cắt",
        cell: (info) => (
          <div className="flex max-w-xl flex-wrap gap-1">
            {mealDays.map((day) => {
              const slot = info.row.original.weekly?.[day] || {};
              const count = Number(!!slot.morning) + Number(!!slot.noon) + Number(!!slot.evening);
              return count ? (
                <Badge key={day} variant="secondary">
                  {day}: {count}/3
                </Badge>
              ) : null;
            })}
          </div>
        ),
      },
      { id: "notes", header: "Ghi chú", accessorKey: "notes" },
      {
        id: "updatedAt",
        header: "Cập nhật",
        cell: (info) => (
          <Typography variant="caption" color="gray">
            {formatDateTime(info.row.original.updatedAt)}
          </Typography>
        ),
      },
      {
        id: "actions",
        header: "Tự động",
        cell: (info) => (
          <ActionButton
            tooltipText="Tạo lại tự động"
            icon={HiOutlineRefresh}
            color="green"
            onClick={() => generateOneMutation.mutate(info.row.original.userId)}
          />
        ),
      },
    ],
    [generateOneMutation]
  );

  const filterOptions = useMemo<FilterField[]>(
    () => [
      {
        type: "text",
        id: "fullName",
        label: "Tên học viên",
        placeholder: "Nhập tên học viên...",
      },
      {
        type: "text",
        id: "userId",
        label: "User ID",
        placeholder: "Nhập userId...",
      },
    ],
    []
  );

  const exportExcel = () => {
    window.open(`${process.env.NEXT_PUBLIC_API_URL}/api/cut-rice/export`, "_blank");
  };

  if (cutRice.isLoading) return <CutRiceSkeleton />;

  if (cutRice.isError) {
    return (
      <ErrorState
        title="Không thể tải lịch cắt cơm"
        message={cutRice.error?.message || "Vui lòng thử lại sau ít phút."}
        onRetry={() => cutRice.refetch()}
      />
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap justify-end gap-3">
        <Button variant="secondary" onClick={exportExcel}>
          <HiOutlineDownload /> Xuất Excel
        </Button>
        <Button
          variant="primary"
          onClick={() => generateAllMutation.mutate()}
          isLoading={generateAllMutation.isPending}
        >
          <HiOutlineRefresh /> Tạo tự động
        </Button>
      </div>

      <Table
        data={cutRice.data}
        columns={columns}
        pagination={cutRice.pagination}
        onPaginationChange={cutRice.setPagination}
        columnFilters={cutRice.columnFilters}
        onColumnFiltersChange={cutRice.setColumnFilters}
        sorting={cutRice.sorting}
        onSortingChange={cutRice.setSorting}
        filterFields={filterOptions}
        emptyText="Không tìm thấy lịch cắt cơm"
      />
    </div>
  );
}
