"use client";

import { useMemo } from "react";
import { ColumnDef } from "@tanstack/react-table";
import { HiOutlineDownload, HiOutlinePencil, HiOutlineRefresh, HiOutlineUpload } from "react-icons/hi";
import ActionButton from "@/library/ActionButton";
import Badge from "@/library/Badge";
import Button from "@/library/Button";
import ErrorState from "@/library/ErrorState";
import Table from "@/library/Table";
import Typography from "@/library/Typography";
import { FilterField } from "@/library/table/TableFilter";
import useAppMutation from "@/hooks/useAppMutation";
import useTableQuery from "@/hooks/useTableQuery";
import { MUTATION_KEYS, QUERY_KEYS } from "@/constants/query-keys";
import { cutRiceService } from "@/services/cut-rice";
import { downloadBlob, formatDateTime } from "@/utils/fn-common";
import { CutRice, CutRiceQueryRequest } from "@/types/cut-rice";
import CutRiceSkeleton from "./CutRiceSkeleton";
import EditCutRiceForm from "./EditCutRiceForm";
import ImportCutRiceForm from "./ImportCutRiceForm";
import { useModalStore } from "@/store/useModalStore";

const mealDays = ["Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ nhật"];

const getCutRiceUser = (record: CutRice) => record.User || record.user;
const getCutRiceProfile = (record: CutRice) => {
  const user = getCutRiceUser(record);
  return user?.Profile || user?.profile;
};
const getStudentName = (record: CutRice) =>
  getCutRiceProfile(record)?.fullName ||
  getCutRiceUser(record)?.username ||
  record.userId;
const getSlot = (record: CutRice, day: string) => {
  const weekly = record.weekly || {};
  return weekly[day] || weekly[day.toLowerCase()] || {};
};

export default function CutRiceTab() {
  const { openModal } = useModalStore();
  const cutRice = useTableQuery<CutRice>({
    queryKey: [QUERY_KEYS.CUT_RICE],
    fetchData: cutRiceService.getCutRiceList,
  });

  const generateAllMutation = useAppMutation({
    mutationKey: MUTATION_KEYS.GENERATE_ALL_CUT_RICE,
    mutationFn: cutRiceService.generateAll,
    invalidateQueryKey: [QUERY_KEYS.CUT_RICE],
    successMessage: "Tạo lịch cắt cơm tự động thành công!",
    errorMessage: "Tạo lịch cắt cơm thất bại!",
  });

  const generateOneMutation = useAppMutation({
    mutationKey: MUTATION_KEYS.GENERATE_CUT_RICE,
    mutationFn: (userId: string) => cutRiceService.generateForStudent(userId),
    invalidateQueryKey: [QUERY_KEYS.CUT_RICE],
    successMessage: "Tạo lại lịch cắt cơm thành công!",
    errorMessage: "Tạo lại lịch cắt cơm thất bại!",
  });

  const exportMutation = useAppMutation({
    mutationKey: [QUERY_KEYS.CUT_RICE, "export"],
    mutationFn: () => {
      const filterParams = cutRice.columnFilters.reduce(
        (acc, filter) => {
          acc[filter.id] = filter.value;
          return acc;
        },
        {} as Record<string, unknown>
      );

      return cutRiceService.exportExcel({
        ...filterParams,
        sortBy: cutRice.sorting[0]?.id,
        sortOrder: cutRice.sorting[0]?.desc ? "desc" : "asc",
      } as CutRiceQueryRequest);
    },
    successMessage: "Xuất Excel thành công!",
    errorMessage: "Xuất Excel thất bại!",
    onSuccess: (blob) => downloadBlob(blob, "lich-cat-com.xlsx"),
  });

  const handleImport = () => {
    openModal({
      title: "Nhập lịch cắt cơm từ Excel",
      content: <ImportCutRiceForm />,
      size: "md",
      config: { mutationKey: [QUERY_KEYS.CUT_RICE, "import"] },
    });
  };

  const columns = useMemo<ColumnDef<CutRice>[]>(
    () => [
      {
        id: "student",
        header: "Học viên",
        meta: { noWrap: true },
        cell: (info) => (
          <div>
            <Typography variant="body" weight="semibold" color="neutral">
              {getStudentName(info.row.original)}
            </Typography>
            <Typography variant="caption" color="gray">
              {getCutRiceProfile(info.row.original)?.code ||
                getCutRiceProfile(info.row.original)?.unit ||
                info.row.original.userId}
            </Typography>
          </div>
        ),
      },
      {
        id: "auto",
        header: "Trạng thái",
        cell: (info) => (
          <Badge variant={info.row.original.isAutoGenerated ? "success" : "warning"}>
            {info.row.original.isAutoGenerated ? "Tự động" : "Thủ công"}
          </Badge>
        ),
      },
      {
        id: "weekly",
        header: "Lịch cắt",
        cell: (info) => (
          <div className="flex max-w-xl flex-wrap gap-1">
            {mealDays.some((day) => {
              const slot = getSlot(info.row.original, day);
              return slot.morning || slot.noon || slot.evening;
            }) ? mealDays.map((day) => {
              const slot = getSlot(info.row.original, day);
              const count = Number(!!slot.morning) + Number(!!slot.noon) + Number(!!slot.evening);
              return count ? (
                <Badge key={day} variant="secondary">
                  {day}: {count}/3
                </Badge>
              ) : null;
            }) : (
              <Typography variant="caption" color="gray">
                Chưa có lịch cắt
              </Typography>
            )}
          </div>
        ),
      },
      {
        id: "notes",
        header: "Ghi chú",
        cell: (info) => (
          <Typography variant="caption" color="gray">
            {info.row.original.notes || "Không có ghi chú"}
          </Typography>
        ),
      },
      {
        id: "updatedAt",
        header: "Cập nhật",
        cell: (info) => (
          <Typography variant="caption" color="gray">
            {formatDateTime(info.row.original.updatedAt)}
          </Typography>
        ),
      },
      {
        id: "actions",
        header: "Thao tác",
        cell: (info) => {
          const record = info.row.original;
          return (
            <div className="flex items-center gap-1">
              <ActionButton
                tooltipText="Chỉnh thủ công"
                icon={HiOutlinePencil}
                color="blue"
                onClick={() =>
                  openModal({
                    title: "Chỉnh lịch cắt cơm",
                    content: <EditCutRiceForm record={record} />,
                    size: "xl",
                  })
                }
              />
              <ActionButton
                tooltipText="Tạo lại tự động"
                icon={HiOutlineRefresh}
                color="green"
                onClick={() => generateOneMutation.mutate(record.userId)}
              />
            </div>
          );
        },
      },
    ],
    [generateOneMutation, openModal]
  );

  const filterOptions = useMemo<FilterField[]>(
    () => [
      {
        type: "text",
        id: "fullName",
        label: "Tên học viên",
        placeholder: "Nhập tên học viên...",
      },
      {
        type: "text",
        id: "userId",
        label: "User ID",
        placeholder: "Nhập userId...",
      },
    ],
    []
  );

  if (cutRice.isLoading) return <CutRiceSkeleton />;

  if (cutRice.isError) {
    return (
      <ErrorState
        title="Không thể tải lịch cắt cơm"
        message={cutRice.error?.message || "Vui lòng thử lại sau ít phút."}
        onRetry={() => cutRice.refetch()}
      />
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap justify-end gap-3">
        <Button
          variant="secondary"
          onClick={handleImport}
        >
          <HiOutlineUpload /> Nhập Excel
        </Button>
        <Button
          variant="secondary"
          onClick={() => exportMutation.mutate()}
          isLoading={exportMutation.isPending}
        >
          <HiOutlineDownload /> Xuất Excel
        </Button>
        <Button
          variant="primary"
          onClick={() => generateAllMutation.mutate()}
          isLoading={generateAllMutation.isPending}
        >
          <HiOutlineRefresh /> Tạo tự động
        </Button>
      </div>

      <Table
        data={cutRice.data}
        columns={columns}
        pagination={cutRice.pagination}
        onPaginationChange={cutRice.setPagination}
        columnFilters={cutRice.columnFilters}
        onColumnFiltersChange={cutRice.setColumnFilters}
        sorting={cutRice.sorting}
        onSortingChange={cutRice.setSorting}
        filterFields={filterOptions}
        emptyText="Không tìm thấy lịch cắt cơm"
      />
    </div>
  );
}
